# Generated by Django 5.2.7 on 2026-01-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_material_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='motivo',
            field=models.CharField(max_length=200),
        ),
    ]
