# Generated by Django 5.2.7 on 2026-01-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimiento_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='stock_resultante',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
