# Generated by Django 5.2.7 on 2026-01-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_movimiento_stock_resultante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='stock_resultante',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
