# Generated by Django 5.2.7 on 2026-02-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_movimiento_stock_resultante'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
